#!/bin/sh
CACHE_DIR="$HOME/.cache/power"

function debloat() { 
  rm "$CACHE_DIR/debloat.lock" 
  swww kill
  killall waybar
  #killall eww
  #hyprctl keyword animations:enabled 0 
}

function bloat() {
  touch "$CACHE_DIR/debloat.lock"
  swww init 
  exec waybar &
  #exec ~/.config/eww/scripts/start.sh
  #hyprctl keyword animations:enabled 1
}

case "$1" in
  "bloat") bloat;;
  "debloat") debloat;;
  *) echo "unknown command";;
esac
